Fix copyright checker
The heredoc had wrong indentation.

diff --git a/.github/workflows/code-formatting.yml b/.github/workflows/code-formatting.yml
--- a/.github/workflows/code-formatting.yml
+++ b/.github/workflows/code-formatting.yml
@@ -143,10 +143,8 @@ jobs:
 
         # Tell user what to do in case of copyright notice error
         if [ -n "$have_err" ]; then
-          cat << EOF >&2
-        ::error::The files listed above are missing the correct copyright notice.
-        ::error::Make sure all your source files begin with the following exact lines:
-        $COPYRIGHT
-        EOF
+          echo '::error::The files listed above are missing the correct copyright notice.' >&2
+          echo '::error::Make sure all your source files begin with the following exact lines:' >&2
+          echo "$COPYRIGHT" >&2
           exit 1
         fi
